[package]
name = "automerge-sync-test"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"

[dependencies]
automerge = { path = "../automerge" }
automerge-backend = { path = "../automerge-backend" }
criterion = "0.3.3"
